name: test-nn

on:
  push:
    branches: [master]

jobs:
  simple-mlp:
    runs-on: ubuntu-latest
    container: pytorchlightning/pytorch_lightning
    name: Test NN inference
    steps:
      - uses: actions/checkout@v2
      - run: | 
          cd $GITHUB_WORKSPACE
          pip install -e .
          mkdir -p $outpath
          python3 tests/data/generate_data.py --out $outpath --nclasses $nclasses --nfeatures $nfeatures --difficulty $difficulty --nexamples $nexamples
          python3 tests/train_$type.py --training $outpath/training.csv --testing $outpath/testing.csv --out $outpath
          python3 -m fastinference --model $outpath/$modelname.onnx --feature_type int --language cpp --out_path $outpath --out_name model
          python3 ./tests/data/convert_data.py --file $outpath/testing.csv --out $outpath/testing.h --dtype int --ltype "unsigned int"
          cp ./tests/main.cpp $outpath
          cp ./tests/CMakeLists.txt $outpath
          cd $outpath
          cmake . -DMODELNAME=$modelname
          make
          ./testCode
        env:
          type: nn
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/nn/cpp/float/
          modelname: SimpleMLP