name: Running tests

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: pytorchlightning/pytorch_lightning
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
            pip install -e .

      - name: Test single QDA
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation
        env:
          type: discriminant
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: DiscriminantAnalysis
          nestimators: 1
          implementation: cpp
      - name: Test bagged QDA
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation --baseimplementation=cpp
        env:
          type: discriminant
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: BaggingDiscriminantAnalysis
          nestimators: 20
          implementation: cpp

      - name: Test DT inference with ifelse backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation
        env:
          type: tree
          nestimators: 1
          maxdepth: 5
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: DecisionTreeClassifier
          implementation: cpp.ifelse

      - name: Test RF inference with ifelse backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation --baseimplementation=$baseimplementation
        env:
          type: tree
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: RandomForestClassifier
          nestimators: 20
          implementation: cpp
          baseimplementation: cpp.ifelse

      - name: Test DT inference with native backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation
        env:
          type: tree
          nestimators: 1
          maxdepth: 5
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: DecisionTreeClassifier
          implementation: cpp.native

      - name: Test RF inference with native backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation --baseimplementation=$baseimplementation
        env:
          type: tree
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: RandomForestClassifier
          nestimators: 20
          implementation: cpp
          baseimplementation: cpp.native

      - name: Test linear inference with native backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation
        env:
          type: linear
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: RidgeClassifier
          nestimators: 1
          implementation: cpp.native

      - name: Test bagged linear inference with native backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation --baseimplementation=$baseimplementation
        env:
          type: linear
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/linear/bagging/
          modelname: BaggingRidgeClassifier
          nestimators: 20
          implementation: cpp
          baseimplementation: cpp.native

      - name: Test linear inference with unroll backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation
        env:
          type: linear
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          modelname: RidgeClassifier
          nestimators: 1
          implementation: cpp.unroll

      - name: Test bagged linear inference with unroll backend
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation --baseimplementation=$baseimplementation
        env:
          type: linear
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/linear/bagging/
          modelname: BaggingRidgeClassifier
          nestimators: 20
          implementation: cpp
          baseimplementation: cpp.unroll

      - name: Test MLP inference
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation
        env:
          type: mlp
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          implementation: cpp.NHWC
          modelname: SimpleMLP
      
      - name: Test binary MLP inference
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation --binarize=on
        env:
          type: mlp
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          implementation: cpp.binary
          modelname: SimpleMLP

      - name: Test CNN inference
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation
        env:
          type: cnn
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          implementation: cpp.NHWC
          modelname: SimpleCNN
    
      - name: Test binary CNN inference
        run: | 
            cd $GITHUB_WORKSPACE
            mkdir -p $outpath
            bash tests/run_test.sh --outpath=$outpath --nclasses=$nclasses --nfeatures=$nfeatures --difficulty=$difficulty --nexamples=$nexamples --type=$type --modelname=$modelname --nestimators=$nestimators --implementation=$implementation --binarize=on
        env:
          type: cnn
          nclasses: 5
          nfeatures: 10
          difficulty: 0.5
          nexamples: 10000
          outpath: /tmp/fastinference/
          implementation: cpp.binary
          modelname: SimpleCNN